[package]
name = "ordinals"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
bitcoin = { version = "0.30.1", features = ["rand"] }
anyhow = { version = "1.0.56", features = ["backtrace"] }

[dev-dependencies]
serde_json = { version = "1.0.81", features = ["preserve_order"] }
