name: Docker

on:
  push:
    tags:
      - '*'

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: ord

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event_name == 'push'
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: >-
          docker buildx build --push 
          --file ./Dockerfile 
          --build-arg TAG=${{ github.ref_name }}
          --tag ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
          --tag ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.ref_name }}
          --platform linux/amd64,linux/arm64 .